package cat.udl.cig.sms.busom.data;

import cat.udl.cig.fields.GroupElement;

import java.math.BigInteger;

/**
 * Groups public and generalKey of a meter.
 * Simplifies abstraction of code.
 */
public final class MeterKey {

    private final GroupElement generalKey;
    private final BigInteger privateKey;

    /**
     * Constructs a MeterKey
     *
     * @param privateKey private key of the meter.
     * @param generalKey general Key of the meter. It's calculated by adding
     *                   all the points generated by privateKey * G, where g
     *                   is the generator and privateKey is the privateKey of every meter.
     */
    public MeterKey(BigInteger privateKey, GroupElement generalKey) {
        this.privateKey = privateKey;
        this.generalKey = generalKey;
    }

    /**
     * Getter of generalKey
     *
     * @return the value of the general Key
     */
    public GroupElement getGeneralKey() {
        return generalKey;
    }

    /**
     * Getter of the privateKey
     *
     * @return the value of the privateKey
     */
    public BigInteger getPrivateKey() {
        return privateKey;
    }
}
